# Generated by Django 5.2.1 on 2025-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="purchase_price",
        ),
        migrations.AddField(
            model_name="product",
            name="author_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email автора"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
